/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this tartlate file, choose Tools | Tartlates
 * and open the tartlate in the editor.
 */
package com.lubrindustrial.View;

import com.lubrindustrial.Server.Department;
import com.lubrindustrial.Server.DepartmentCRUD;
import com.lubrindustrial.Server.Employee;
import com.lubrindustrial.Server.EmployeeCRUD;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import com.lubrindustrial.Server.Equipment;
import com.lubrindustrial.Server.EquipmentCRUD;
import com.lubrindustrial.Server.Location;
import com.lubrindustrial.Server.LocationCRUD;
import com.lubrindustrial.Server.User;
import static com.lubrindustrial.View.Home.escritorio;
import java.awt.Dimension;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Icon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import javax.swing.table.DefaultTableModel;


public class EquipmentView extends javax.swing.JInternalFrame {

    ArrayList<Employee> empleados = new ArrayList<Employee>();
    ArrayList<Location> locaciones = new ArrayList<Location>();
    ArrayList<Equipment> equipos = new ArrayList<Equipment>();
    User user = new User();
    public static String ruta="";

    public EquipmentView() {
        try{
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
        initComponents();
                //System.out.println("ruta txt: "+txt_foto1.getText());
        //txt_foto.setVisible(false);
        this.setIconifiable(true);
        this.setClosable(true);
        lblID.setVisible(false);
        lblID.setEnabled(false);
//        this.setLocationRelativeTo(null);
//        rsscalelabel.RSScaleLabel.setScaleLabel(lblImage, "carburador.jpg");
        cargarFoto();

    }

    public EquipmentView(User us) {
        try{
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
        initComponents();
        //System.out.println("ruta txt: "+txt_foto1.getText());
        //txt_foto.setVisible(false);
        this.setIconifiable(true);
        this.setClosable(true);
        lblID.setVisible(false);
        lblID.setEnabled(false);
        
        user = us;
        cargarFoto();
    }
    
    private void Volver(){
        Equipments obj = new Equipments();
        Home.escritorio.add(obj);
        obj.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = obj.getSize();
        obj.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        obj.show();
    }
    
    private void cargarFoto(){
//        ruta="C:\\Users\\Marcelo\\Desktop\\LUBRINDUSTRIALES_TRABAJO\\FINAL_OCTUBRE\\Lubrindustrial-master\\FotosEquipos\\cald.jpg";
        //ruta=txt_foto1.getText();
        System.out.println("ruta: "+ruta);
        try{
            ImageIcon icon = new ImageIcon(ruta);
            Icon icono = new ImageIcon(icon.getImage().getScaledInstance(110, 110, Image.SCALE_DEFAULT));
            lblImage.setText(null);            
            lblImage.setIcon( icono );
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error abriendo la imagen "+ ex);       
        }
    }
    
     public static Date ParseFecha(String fecha)
    {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaDate = null;
        try {
            fechaDate = formato.parse(fecha);
        } 
        catch (ParseException ex) 
        {
            System.out.println(ex);
        }
        return fechaDate;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txt_DescEquipment = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txt_NroModEquipment = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_NroSerieEquipment = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txt_TipoEquipment = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txt_EstadoEquipment = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_FabricEquipment = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txt_FechaCompEquipment = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txt_FechaVentEquipment = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txt_ContratistaEquipment = new javax.swing.JTextField();
        txt_EqPadre = new javax.swing.JTextField();
        btnCancelar1 = new javax.swing.JButton();
        txt_FechaIniEquipment = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txt_foto1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        txt_NroEquipment1 = new javax.swing.JTextField();
        txt_Locacion = new javax.swing.JTextField();
        txt_Responsable = new javax.swing.JTextField();
        txt_Piezas1 = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(true);
        setTitle("Detalles de Equipo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Equipo Padre");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        jLabel25.setText("Descripción");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        txt_DescEquipment.setEditable(false);
        txt_DescEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DescEquipmentActionPerformed(evt);
            }
        });
        txt_DescEquipment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_DescEquipmentKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_DescEquipmentKeyTyped(evt);
            }
        });
        jPanel4.add(txt_DescEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 153, -1));

        jLabel26.setText("No. Modelo");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        txt_NroModEquipment.setEditable(false);
        txt_NroModEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NroModEquipmentActionPerformed(evt);
            }
        });
        txt_NroModEquipment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_NroModEquipmentKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NroModEquipmentKeyTyped(evt);
            }
        });
        jPanel4.add(txt_NroModEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 153, -1));

        jLabel27.setText("No. Serie");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 20));

        txt_NroSerieEquipment.setEditable(false);
        txt_NroSerieEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NroSerieEquipmentActionPerformed(evt);
            }
        });
        txt_NroSerieEquipment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_NroSerieEquipmentKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NroSerieEquipmentKeyTyped(evt);
            }
        });
        jPanel4.add(txt_NroSerieEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 153, -1));

        jLabel28.setText("Tipo de Equipo");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        txt_TipoEquipment.setEditable(false);
        txt_TipoEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TipoEquipmentActionPerformed(evt);
            }
        });
        txt_TipoEquipment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TipoEquipmentKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_TipoEquipmentKeyTyped(evt);
            }
        });
        jPanel4.add(txt_TipoEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 153, -1));

        jLabel29.setText("Estado");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, 20));

        txt_EstadoEquipment.setEditable(false);
        txt_EstadoEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EstadoEquipmentActionPerformed(evt);
            }
        });
        txt_EstadoEquipment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_EstadoEquipmentKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_EstadoEquipmentKeyTyped(evt);
            }
        });
        jPanel4.add(txt_EstadoEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 153, -1));

        jLabel30.setText("No. de Equipo");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        jLabel31.setText("Fabricante");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, 20));

        txt_FabricEquipment.setEditable(false);
        txt_FabricEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FabricEquipmentActionPerformed(evt);
            }
        });
        txt_FabricEquipment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_FabricEquipmentKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_FabricEquipmentKeyTyped(evt);
            }
        });
        jPanel4.add(txt_FabricEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 153, -1));

        jLabel32.setText("Fecha de Compra");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, 20));

        txt_FechaCompEquipment.setEditable(false);
        txt_FechaCompEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FechaCompEquipmentActionPerformed(evt);
            }
        });
        txt_FechaCompEquipment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_FechaCompEquipmentKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_FechaCompEquipmentKeyTyped(evt);
            }
        });
        jPanel4.add(txt_FechaCompEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 153, -1));

        jLabel33.setText("Fecha Inicial");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, 20));

        txt_FechaVentEquipment.setEditable(false);
        txt_FechaVentEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FechaVentEquipmentActionPerformed(evt);
            }
        });
        txt_FechaVentEquipment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_FechaVentEquipmentKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_FechaVentEquipmentKeyTyped(evt);
            }
        });
        jPanel4.add(txt_FechaVentEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 153, -1));

        jLabel34.setText("Fecha de Venta");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, 20));

        jLabel35.setText("Contratista");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, 20));

        txt_ContratistaEquipment.setEditable(false);
        txt_ContratistaEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ContratistaEquipmentActionPerformed(evt);
            }
        });
        txt_ContratistaEquipment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_ContratistaEquipmentKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ContratistaEquipmentKeyTyped(evt);
            }
        });
        jPanel4.add(txt_ContratistaEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 153, -1));

        txt_EqPadre.setEditable(false);
        txt_EqPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EqPadreActionPerformed(evt);
            }
        });
        txt_EqPadre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_EqPadreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_EqPadreKeyTyped(evt);
            }
        });
        jPanel4.add(txt_EqPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 153, -1));

        btnCancelar1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/cancelar.png"))); // NOI18N
        btnCancelar1.setText("Cerrar");
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 150, -1));

        txt_FechaIniEquipment.setEditable(false);
        txt_FechaIniEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FechaIniEquipmentActionPerformed(evt);
            }
        });
        txt_FechaIniEquipment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_FechaIniEquipmentKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_FechaIniEquipmentKeyTyped(evt);
            }
        });
        jPanel4.add(txt_FechaIniEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 153, -1));

        jLabel9.setText("Id de Locación");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        jLabel10.setText("Responsable");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jLabel36.setText("Piezas");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, 20));

        txt_foto1.setEditable(false);
        txt_foto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_foto1ActionPerformed(evt);
            }
        });
        txt_foto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_foto1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_foto1KeyTyped(evt);
            }
        });
        jPanel4.add(txt_foto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 153, -1));

        jLabel37.setText("Imagen");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, 20));

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setText("Imagen");
        lblImage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblImage.setPreferredSize(new java.awt.Dimension(45, 15));
        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImageMouseClicked(evt);
            }
        });
        jPanel4.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 110, 110));

        txt_NroEquipment1.setEditable(false);
        txt_NroEquipment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NroEquipment1ActionPerformed(evt);
            }
        });
        txt_NroEquipment1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_NroEquipment1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NroEquipment1KeyTyped(evt);
            }
        });
        jPanel4.add(txt_NroEquipment1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 153, -1));

        txt_Locacion.setEditable(false);
        txt_Locacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_LocacionActionPerformed(evt);
            }
        });
        txt_Locacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_LocacionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_LocacionKeyTyped(evt);
            }
        });
        jPanel4.add(txt_Locacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 153, -1));

        txt_Responsable.setEditable(false);
        txt_Responsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ResponsableActionPerformed(evt);
            }
        });
        txt_Responsable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_ResponsableKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ResponsableKeyTyped(evt);
            }
        });
        jPanel4.add(txt_Responsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 153, -1));

        txt_Piezas1.setEditable(false);
        txt_Piezas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Piezas1ActionPerformed(evt);
            }
        });
        txt_Piezas1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_Piezas1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_Piezas1KeyTyped(evt);
            }
        });
        jPanel4.add(txt_Piezas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 153, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 660, 360));
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 40, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_DescEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DescEquipmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DescEquipmentActionPerformed

    private void txt_DescEquipmentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DescEquipmentKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DescEquipmentKeyReleased

    private void txt_DescEquipmentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DescEquipmentKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DescEquipmentKeyTyped

    private void txt_NroModEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NroModEquipmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NroModEquipmentActionPerformed

    private void txt_NroModEquipmentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NroModEquipmentKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NroModEquipmentKeyReleased

    private void txt_NroModEquipmentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NroModEquipmentKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NroModEquipmentKeyTyped

    private void txt_NroSerieEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NroSerieEquipmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NroSerieEquipmentActionPerformed

    private void txt_NroSerieEquipmentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NroSerieEquipmentKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NroSerieEquipmentKeyReleased

    private void txt_NroSerieEquipmentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NroSerieEquipmentKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NroSerieEquipmentKeyTyped

    private void txt_TipoEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TipoEquipmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TipoEquipmentActionPerformed

    private void txt_TipoEquipmentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TipoEquipmentKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TipoEquipmentKeyReleased

    private void txt_TipoEquipmentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TipoEquipmentKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TipoEquipmentKeyTyped

    private void txt_EstadoEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EstadoEquipmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EstadoEquipmentActionPerformed

    private void txt_EstadoEquipmentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_EstadoEquipmentKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EstadoEquipmentKeyReleased

    private void txt_EstadoEquipmentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_EstadoEquipmentKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EstadoEquipmentKeyTyped

    private void txt_FabricEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FabricEquipmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FabricEquipmentActionPerformed

    private void txt_FabricEquipmentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_FabricEquipmentKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FabricEquipmentKeyReleased

    private void txt_FabricEquipmentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_FabricEquipmentKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FabricEquipmentKeyTyped

    private void txt_FechaCompEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FechaCompEquipmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FechaCompEquipmentActionPerformed

    private void txt_FechaCompEquipmentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_FechaCompEquipmentKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FechaCompEquipmentKeyReleased

    private void txt_FechaCompEquipmentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_FechaCompEquipmentKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FechaCompEquipmentKeyTyped

    private void txt_FechaVentEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FechaVentEquipmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FechaVentEquipmentActionPerformed

    private void txt_FechaVentEquipmentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_FechaVentEquipmentKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FechaVentEquipmentKeyReleased

    private void txt_FechaVentEquipmentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_FechaVentEquipmentKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FechaVentEquipmentKeyTyped

    private void txt_ContratistaEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ContratistaEquipmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ContratistaEquipmentActionPerformed

    private void txt_ContratistaEquipmentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ContratistaEquipmentKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ContratistaEquipmentKeyReleased

    private void txt_ContratistaEquipmentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ContratistaEquipmentKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ContratistaEquipmentKeyTyped

    private void txt_EqPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EqPadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EqPadreActionPerformed

    private void txt_EqPadreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_EqPadreKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EqPadreKeyReleased

    private void txt_EqPadreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_EqPadreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EqPadreKeyTyped

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        Volver();
        this.dispose();

    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void txt_FechaIniEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FechaIniEquipmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FechaIniEquipmentActionPerformed

    private void txt_FechaIniEquipmentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_FechaIniEquipmentKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FechaIniEquipmentKeyReleased

    private void txt_FechaIniEquipmentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_FechaIniEquipmentKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FechaIniEquipmentKeyTyped

    private void txt_foto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_foto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_foto1ActionPerformed

    private void txt_foto1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_foto1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_foto1KeyReleased

    private void txt_foto1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_foto1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_foto1KeyTyped

    private void txt_NroEquipment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NroEquipment1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NroEquipment1ActionPerformed

    private void txt_NroEquipment1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NroEquipment1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NroEquipment1KeyReleased

    private void txt_NroEquipment1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NroEquipment1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NroEquipment1KeyTyped

    private void txt_LocacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_LocacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LocacionActionPerformed

    private void txt_LocacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_LocacionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LocacionKeyReleased

    private void txt_LocacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_LocacionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LocacionKeyTyped

    private void txt_ResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ResponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ResponsableActionPerformed

    private void txt_ResponsableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ResponsableKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ResponsableKeyReleased

    private void txt_ResponsableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ResponsableKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ResponsableKeyTyped

    private void txt_Piezas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Piezas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Piezas1ActionPerformed

    private void txt_Piezas1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Piezas1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Piezas1KeyReleased

    private void txt_Piezas1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Piezas1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Piezas1KeyTyped

    private void lblImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseClicked
        // TODO add your handling code here:
        frmFotoMaximiza obj = new frmFotoMaximiza(ruta);
        obj.show();
    }//GEN-LAST:event_lblImageMouseClicked
public void validarletra(java.awt.event.KeyEvent evt)
{
    char c=evt.getKeyChar();
        if((c<'a' || c>'z')&&(c<'A' || c>'Z'))
            evt.consume();
}    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JLabel lblID;
    private javax.swing.JLabel lblImage;
    public static javax.swing.JTextField txt_ContratistaEquipment;
    public static javax.swing.JTextField txt_DescEquipment;
    public static javax.swing.JTextField txt_EqPadre;
    public static javax.swing.JTextField txt_EstadoEquipment;
    public static javax.swing.JTextField txt_FabricEquipment;
    public static javax.swing.JTextField txt_FechaCompEquipment;
    public static javax.swing.JTextField txt_FechaIniEquipment;
    public static javax.swing.JTextField txt_FechaVentEquipment;
    public static javax.swing.JTextField txt_Locacion;
    public static javax.swing.JTextField txt_NroEquipment1;
    public static javax.swing.JTextField txt_NroModEquipment;
    public static javax.swing.JTextField txt_NroSerieEquipment;
    public static javax.swing.JTextField txt_Piezas1;
    public static javax.swing.JTextField txt_Responsable;
    public static javax.swing.JTextField txt_TipoEquipment;
    public static javax.swing.JTextField txt_foto1;
    // End of variables declaration//GEN-END:variables
}
