/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lubrindustrial.View;

import com.lubrindustrial.Server.Article;
import com.lubrindustrial.Server.ArticleCRUD;
import com.lubrindustrial.Server.Department;
import com.lubrindustrial.Server.DepartmentCRUD;
import com.lubrindustrial.Server.Employee;
import com.lubrindustrial.Server.EmployeeCRUD;
import com.lubrindustrial.Server.PEDIDOMATERIAL;
import com.lubrindustrial.Server.PEDIDOMATERIALCRUD;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 *
 * @author Marcelo
 */
public class frmPedidoMateriales extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmPedidoMateriales
     */
    
//    ArrayList<Department> departamentos = new ArrayList<Department>();
    ArrayList<Employee> empleados = new ArrayList<Employee>();
    ArrayList<Article> articulos = new ArrayList<Article>();
    String host;
    
    public frmPedidoMateriales() {
        try{
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
        initComponents();
        this.setIconifiable(true);
        this.setClosable(true);
        //llenarComboBoxDepartamentos();
        llenarComboBoxEmpleados();
        llenarComboBoxArticulos();
    }
    
    public frmPedidoMateriales(String hostname) {
        try{
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
        initComponents();
        this.setIconifiable(true);
        this.setClosable(true);
        host=hostname;
        //llenarComboBoxDepartamentos();
        llenarComboBoxEmpleados();
        llenarComboBoxArticulos();
    }
    
//    private void llenarComboBoxDepartamentos(){
//        DepartmentCRUD deptCRUD = new DepartmentCRUD();
//        
//        departamentos = deptCRUD.visualizar(); // devuelve todos los registros de la BD
//        
//        cmbox_departamentos.removeAllItems();
//        
//        for(Department d: departamentos){  
//            cmbox_departamentos.addItem(d.getIdDepartment()+" "+d.getDescDepartment());
//        }
//    }
    
    private void llenarComboBoxEmpleados(){
        EmployeeCRUD empsCRUD = new EmployeeCRUD(host);
//        int idDep=0;
//        
//        String dep = cmbox_departamentos.getSelectedItem().toString();
//        String []cad = dep.split(" ");
//        idDep = Integer.parseInt(cad[0]);
        
        empleados = empsCRUD.visualizarPorDepartamento(1); // devuelve todos los registros de la BD
        
        cmbox_EmpPedido.removeAllItems();
        cmbox_EmpEntregado.removeAllItems();
        cmbox_EmpAprobado.removeAllItems();
        cmbox_EmpAutorizado.removeAllItems();
        
        for(Employee e: empleados){  
            cmbox_EmpPedido.addItem(e.getIdEmployee()+" "+e.getNomEmployee()+" "+e.getApeEmployee()+" "+e.getNameDept());
            cmbox_EmpEntregado.addItem(e.getIdEmployee()+" "+e.getNomEmployee()+" "+e.getApeEmployee()+" "+e.getNameDept());
            cmbox_EmpAprobado.addItem(e.getIdEmployee()+" "+e.getNomEmployee()+" "+e.getApeEmployee()+" "+e.getNameDept());
            cmbox_EmpAutorizado.addItem(e.getIdEmployee()+" "+e.getNomEmployee()+" "+e.getApeEmployee()+" "+e.getNameDept());
        }
    }
    
    private void llenarComboBoxArticulos(){
        ArticleCRUD artsCRUD = new ArticleCRUD(host);
        
        articulos = artsCRUD.visualizarSTOCK(); // devuelve todos los registros de la BD
        
        cmbox_materiales.removeAllItems();
        
        for(Article a: articulos){  
            cmbox_materiales.addItem(a.getIdArt()+"- "+a.getNroArt()+" "+a.getDescArt()+": "+a.getCantidad()+" "+a.getDescripCantidad());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbox_materiales = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbox_departamentos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbox_EmpPedido = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbox_EmpEntregado = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbox_EmpAutorizado = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbox_EmpAprobado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_unidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_desc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_fechaSolicitud = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_fechaEntrega = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbox_materiales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Seleccione el material");

        jLabel2.setText("Seleccione el departamento");
        jLabel2.setEnabled(false);

        cmbox_departamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbox_departamentos.setEnabled(false);

        jLabel3.setText("Pedido por (Empleado)");

        cmbox_EmpPedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Entregado a (Empleado)");

        cmbox_EmpEntregado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Autorizado por (Empleado)");

        cmbox_EmpAutorizado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Aprobado por (Empleado)");

        cmbox_EmpAprobado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Cantidad");

        jLabel8.setText("Unidad");

        jLabel9.setText("Descripción");

        jLabel10.setText("Fecha Hora Solicitud");

        jLabel11.setText("Fecha Hora Entrega");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jButton2.setText("Cerrar");

        btnGuardar1.setText("Buscar Empleados Por Departamento");
        btnGuardar1.setEnabled(false);
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(239, 239, 239)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txt_unidad, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                    .addComponent(txt_desc)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cantidad)
                            .addComponent(txt_fechaSolicitud))
                        .addGap(282, 282, 282))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fechaEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbox_materiales, javax.swing.GroupLayout.Alignment.LEADING, 0, 250, Short.MAX_VALUE)
                                    .addComponent(cmbox_departamentos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbox_EmpPedido, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbox_EmpEntregado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbox_EmpAutorizado, 0, 250, Short.MAX_VALUE)
                                    .addComponent(jLabel6)
                                    .addComponent(cmbox_EmpAprobado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addComponent(btnGuardar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbox_materiales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_unidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbox_departamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbox_EmpPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbox_EmpAutorizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbox_EmpEntregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbox_EmpAprobado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_fechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fechaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(jButton2))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        // TODO add your handling code here:
        llenarComboBoxEmpleados();
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        PEDIDOMATERIALCRUD pedCRUD = new PEDIDOMATERIALCRUD(host);
        PEDIDOMATERIAL ped = new PEDIDOMATERIAL();
        String cad="";
        int idAux=0;
        float stock=0;
        String cadStock="";
        
        try{
            cad=cmbox_materiales.getSelectedItem().toString();
            String []split = cad.split("-");
            cad = split[0];
            idAux=Integer.parseInt(cad);
            ped.setIdArt(idAux);
            
            cad=cmbox_EmpPedido.getSelectedItem().toString();
            String []split2 = cad.split(" ");
            cad = split2[0];
            idAux=Integer.parseInt(cad);
            ped.setIdEmpPedido(idAux);
            
            cad=cmbox_EmpEntregado.getSelectedItem().toString();
            String []split3 = cad.split(" ");
            cad = split3[0];
            idAux=Integer.parseInt(cad);
            ped.setIdEmpEntregado(idAux);
            
            cad=cmbox_EmpAutorizado.getSelectedItem().toString();
            String []split4 = cad.split(" ");
            cad = split4[0];
            idAux=Integer.parseInt(cad);
            ped.setIdEmpAutorizado(idAux);
            
            cad=cmbox_EmpAprobado.getSelectedItem().toString();
            String []split5 = cad.split(" ");
            cad = split5[0];
            idAux=Integer.parseInt(cad);
            ped.setIdEmpAprobado(idAux);
            
            ped.setCantidad(Float.parseFloat(txt_cantidad.getText()));
            ped.setUnidadCantidad(txt_unidad.getText());
            ped.setDescripcion(txt_desc.getText());
            ped.setFechaHoraEntrega(txt_fechaEntrega.getText());
            ped.setFechaHoraSolicitud(txt_fechaSolicitud.getText());
            
            // a.getIdArt()+"- "+a.getNroArt()+" "+a.getDescArt()+": "+a.getCantidad()+" "+a.getDescripCantidad()
            cadStock = cmbox_materiales.getSelectedItem().toString();
            String []words = cadStock.split(":");
            String []words1 = words[1].split(" ");
            stock = Float.parseFloat(words1[1]);
            //JOptionPane.showMessageDialog(null, "STOCK: "+stock,"STOCK ACTUAL",JOptionPane.INFORMATION_MESSAGE);
            if(ped.getCantidad()>stock){
                JOptionPane.showMessageDialog(null, "NO EXISTE LA CANTIDAD SOLICITADO EN STOCK DEL MATERIAL. REVISE QUE SEA CORRECTA E INFERIOR A LA DISPONIBLE","ERROR STOCK", JOptionPane.ERROR_MESSAGE);
            }else{
                if(pedCRUD.insertar(ped)){
                    JOptionPane.showMessageDialog(null, "PEDIDO REGISTRADO","REGISTRO EXITOSO",JOptionPane.INFORMATION_MESSAGE);
                    llenarComboBoxEmpleados();
                    llenarComboBoxArticulos();
                //Volver();
                }else{
                    JOptionPane.showMessageDialog(null, "PEDIDO NO REGISTRADO","ERROR EN EL REGISTRO", JOptionPane.ERROR_MESSAGE);
                }
            }
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error obtener los datos: "+e.getMessage(), "ERROR DATOS", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmPedidoMateriales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmPedidoMateriales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmPedidoMateriales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmPedidoMateriales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmPedidoMateriales().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JComboBox<String> cmbox_EmpAprobado;
    private javax.swing.JComboBox<String> cmbox_EmpAutorizado;
    private javax.swing.JComboBox<String> cmbox_EmpEntregado;
    private javax.swing.JComboBox<String> cmbox_EmpPedido;
    private javax.swing.JComboBox<String> cmbox_departamentos;
    private javax.swing.JComboBox<String> cmbox_materiales;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_desc;
    private javax.swing.JTextField txt_fechaEntrega;
    private javax.swing.JTextField txt_fechaSolicitud;
    private javax.swing.JTextField txt_unidad;
    // End of variables declaration//GEN-END:variables
}
