/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lubrindustrial.View;

import com.lubrindustrial.Server.Employee;
import com.lubrindustrial.Server.Hasher;
import com.lubrindustrial.Server.User;
import com.lubrindustrial.Server.UserCRUD;
import java.awt.Cursor;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import javax.swing.table.DefaultTableModel;


public class Login extends javax.swing.JFrame {

    Cursor cursor_mano = new Cursor(Cursor.HAND_CURSOR);
    Cursor cursor_normal = new Cursor(Cursor.DEFAULT_CURSOR);
    
    DefaultTableModel modelo=new DefaultTableModel();
    ArrayList<User> use = new ArrayList<User>();
    
    public static int cuentaEmpleado; 
    
    public Login() {
        try{
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
        initComponents();
        this.setLocationRelativeTo(null);
        lbl_PassForgot.setForeground(Color.BLACK);
        lbl_register.setForeground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtCuenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbl_register = new javax.swing.JLabel();
        lbl_PassForgot = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Ingreso de Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 50, 181, -1));

        txtPass.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 192, 196, -1));

        txtCuenta.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        txtCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 131, 196, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Id de Usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Contraseña");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/ingresar.png"))); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.setName(""); // NOI18N
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 110, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/login.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 320));

        lbl_register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_register.setText("Registrarse");
        lbl_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_registerMouseExited(evt);
            }
        });
        jPanel1.add(lbl_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 90, -1));

        lbl_PassForgot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_PassForgot.setText("¿Olvidó su contraseña?");
        lbl_PassForgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_PassForgotMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_PassForgotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_PassForgotMouseExited(evt);
            }
        });
        jPanel1.add(lbl_PassForgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 150, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Dirección Equipo Servidor");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        txtHost.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        txtHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHostActionPerformed(evt);
            }
        });
        jPanel1.add(txtHost, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 196, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int contador = 0;
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        try{
        if(txtCuenta.getText().length() > 0 && txtPass.getText().length() > 0){
            
            String datos[] = new String[8];//ARRAY DE 8
            UserCRUD query = new UserCRUD(txtHost.getText());
            //System.out.println(txtHost.getText());
            use = query.visualizar(txtCuenta.getText());
            
            for (User u : use) {
                JOptionPane.showMessageDialog(null, "Usuario: "+u.getIdUser() + " - " + u.getNomUser() + " - " + u.getApeUser() + " - " + u.getPassUser(), "Usuario", JOptionPane.WARNING_MESSAGE);
                datos[0] = Integer.toString(u.getIdUser());
                datos[1] = u.getNomUser();
                datos[2] = u.getApeUser();
                datos[3] = u.getPreg1User();
                datos[4] = u.getPreg2User();
                datos[5] = u.getUsuUser();
                datos[6] = u.getPassUser();
                datos[7] = Integer.toString(u.getActivoUser());

            }
            
            for (int i=0;i<datos.length;i++)
            {
                System.out.println(datos[i]);
            }

            if(datos[7].equals("1")){
                if(datos[6].equals(Hasher.convertToMD5(Hasher.convertToSHA1(Hasher.convertToSHA1(txtPass.getText())))) == true){
                    Home obj = new Home(query.obtenerUsuario(txtCuenta.getText()),txtHost.getText());
                    System.out.println("");
                    obj.setVisible(true);
                    obj.setEnabled(true);
                    obj.lblCuenta.setText(txtCuenta.getText());
                    obj.lblNomApe.setText("Bienvenido/a " + datos[1] + " " + datos[2]);
                    
                    System.out.println("cuenta: " + datos[5]);
                    cuentaEmpleado = Integer.parseInt(txtCuenta.getText());
                    this.dispose();
                }
                else{
                    contador++;
                    JOptionPane.showMessageDialog(null, "Datos incorrectos. Número de intentos: " + contador, "Incorrecto", JOptionPane.WARNING_MESSAGE);
                    if(contador == 3){
                        JOptionPane.showMessageDialog(null, "Ha llegado al número máximo de intentos" + contador, "Cerrando...", JOptionPane.WARNING_MESSAGE);
                        System.exit(0);
                    }
                }
            }else{
                JOptionPane.showMessageDialog(null, "El usuario se encuentra deshabilitado, no puede ingresar", "Usuario Inhabilitado", JOptionPane.WARNING_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe ingresar todos los campos", "Completar", JOptionPane.WARNING_MESSAGE);
        }
        }catch(Exception e){
            
        JOptionPane.showMessageDialog(null, "No se ha encontrado el usuario "+e.getMessage(), "Usuario no registrado", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentaActionPerformed

    private void lbl_PassForgotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PassForgotMouseEntered

        lbl_PassForgot.setForeground(Color.blue);
        try {
            lbl_PassForgot.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        } finally {
            lbl_PassForgot.setCursor(Cursor.getDefaultCursor());
}
        
    }//GEN-LAST:event_lbl_PassForgotMouseEntered

    private void lbl_PassForgotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PassForgotMouseExited
        
        lbl_PassForgot.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_lbl_PassForgotMouseExited

    private void lbl_registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_registerMouseEntered

        lbl_register.setForeground(Color.blue);
        
    }//GEN-LAST:event_lbl_registerMouseEntered

    private void lbl_registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_registerMouseExited

        lbl_register.setForeground(Color.black);
        
    }//GEN-LAST:event_lbl_registerMouseExited

    private void lbl_PassForgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_PassForgotMouseClicked

        ValidateQuestion res = new ValidateQuestion(txtHost.getText());
        res.setVisible(true);
        res.setEnabled(true);
        this.dispose();
        
    }//GEN-LAST:event_lbl_PassForgotMouseClicked

    private void lbl_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_registerMouseClicked
       
        RegisterNew reg = new RegisterNew(txtHost.getText());
        reg.setVisible(true);
        reg.setEnabled(true);
        this.dispose();
        
    }//GEN-LAST:event_lbl_registerMouseClicked

    private void txtHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_PassForgot;
    private javax.swing.JLabel lbl_register;
    public static javax.swing.JTextField txtCuenta;
    public static javax.swing.JTextField txtHost;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
