/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lubrindustrial.View;

import com.lubrindustrial.Server.Article;
import com.lubrindustrial.Server.ArticleCRUD;
import com.lubrindustrial.Server.OPERABILIDAD;
import com.lubrindustrial.Server.OPERABILIDADCRUD;
import com.lubrindustrial.Server.ReportsExcel;
import static com.lubrindustrial.View.Home.escritorio;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcelo
 */
public class Operabilidad extends javax.swing.JInternalFrame {

    /**
     * Creates new form Operabilidad
     */
    
    ArrayList<OPERABILIDAD> operabilidades = new ArrayList<OPERABILIDAD>();
    String host;
    public Operabilidad() {
        try{
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
        initComponents();
        this.setIconifiable(true);
        this.setClosable(true);
        host="";
        agregarDatos();
        
    }
    
    public Operabilidad(String hostname) {
        try{
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
        initComponents();
        this.setIconifiable(true);
        this.setClosable(true);
        this.host=hostname;
        agregarDatos();
    }
    
    private void agregarDatos() {
        // ********** CAMBIO PARA MOSTRAR LAS 2 NUEVAS COLUMNAS DE LA BD

        DefaultTableModel model = (DefaultTableModel) tab_operabilidad.getModel();

        model.setRowCount(0);
        String datos[] = new String[3];//ARRAY DE 3

        //LE PASO AL ARRAY LOS DATOS DEL ARRAYLIST 
        OPERABILIDADCRUD opeCRUD = new OPERABILIDADCRUD(host);

        operabilidades = opeCRUD.visualizar(); // devuelve todos los registros de la BD

        for (OPERABILIDAD o : operabilidades) {

            datos[0] = o.getIdOp()+"";
            datos[1] = o.getDescEquipo();
            datos[2] = o.getDescripcion();
            
            model.addRow(datos);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab_operabilidad = new javax.swing.JTable();
        btnShowAll = new javax.swing.JButton();
        btnNewPer = new javax.swing.JButton();
        btnShowPer = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setTitle("Operabilidad");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab_operabilidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Operabilidad", "Equipo", "Descripción Operabilidad"
            }
        ));
        tab_operabilidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_operabilidadMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tab_operabilidad);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 520, 150));

        btnShowAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/show_all.png"))); // NOI18N
        btnShowAll.setText("Mostrar todo");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });
        jPanel1.add(btnShowAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        btnNewPer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/nuevo.png"))); // NOI18N
        btnNewPer.setText("Nuevo Período");
        btnNewPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPerActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        btnShowPer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/edit.png"))); // NOI18N
        btnShowPer.setText("Ver Períodos");
        btnShowPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPerActionPerformed(evt);
            }
        });
        jPanel1.add(btnShowPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/excel_logo.png"))); // NOI18N
        jButton5.setToolTipText("Generar hoja de cálculo de Excel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 40, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab_operabilidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_operabilidadMouseClicked

    }//GEN-LAST:event_tab_operabilidadMouseClicked

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        // TODO add your handling code here:
        agregarDatos();
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void btnNewPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPerActionPerformed
        // TODO add your handling code here:
        PeriodoNew obj = new PeriodoNew(host);
        Home.escritorio.add(obj);
        obj.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = obj.getSize();
        obj.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        obj.show();
    }//GEN-LAST:event_btnNewPerActionPerformed

    private void btnShowPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPerActionPerformed

        Periodos obj = new Periodos(host);
        Home.escritorio.add(obj);
        obj.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = obj.getSize();
        obj.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        obj.show();
        
    }//GEN-LAST:event_btnShowPerActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        ReportsExcel reporte = new ReportsExcel(host);
        OPERABILIDADCRUD eqCRUD = new OPERABILIDADCRUD(host);
        ArrayList<OPERABILIDAD> ope = eqCRUD.visualizar();
        if(reporte.escribirExcelOperabilidad(ope)){
            JOptionPane.showMessageDialog(null, "ARCHIVO EXCEL DE OPERABILIDAD CREADO","ARCHIVO GUARDADO EXITOSAMENTE",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "ARCHIVO EXCEL DE OPERABILIDAD NO CREADO","EROOR EN GUARDADO", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Operabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Operabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Operabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Operabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Operabilidad().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewPer;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JButton btnShowPer;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tab_operabilidad;
    // End of variables declaration//GEN-END:variables
}
