/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lubrindustrial.View;

import com.lubrindustrial.Server.MantenimientoCRUD;
import com.lubrindustrial.Server.Mantenimientos;
import com.lubrindustrial.Server.OrdenTrabajoCRUD;
import com.lubrindustrial.Server.OrdenTrabajos;
import com.lubrindustrial.Server.ReportsExcel;
import com.lubrindustrial.Server.User;
import static com.lubrindustrial.View.Home.escritorio;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jhonny
 */
public class OrdenTrabajo extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    ArrayList<OrdenTrabajos> ot = new ArrayList<OrdenTrabajos>();
    User user = new User();
    String host="";
    /**
     * Creates new form OrdenTrabajo
     */
    public OrdenTrabajo() {
        try {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
        initComponents();
        this.setIconifiable(true);
        this.setClosable(true);
        agregarDatos();
        tab_ordentrabajo.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tab_ordentrabajo.doLayout();
    }

    public OrdenTrabajo(User usu) {
        try {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
        initComponents();
        this.setIconifiable(true);
        this.setClosable(true);
        agregarDatos();
        tab_ordentrabajo.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tab_ordentrabajo.doLayout();
        user = usu;
    }
    
    public OrdenTrabajo(User usu, String hostname) {
        try {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
        initComponents();
        this.setIconifiable(true);
        this.setClosable(true);
        
        tab_ordentrabajo.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tab_ordentrabajo.doLayout();
        user = usu;
        host=hostname;
        agregarDatos();
    }
    
    public int seleccionaritem() {
        int item = cbox.getSelectedIndex();
        return item;
    }

    private void agregarDatos() {

        DefaultTableModel model = (DefaultTableModel) tab_ordentrabajo.getModel();

        model.setRowCount(0);
        String datos[] = new String[19];//ARRAY DE 13

        //LE PASO AL ARRAY LOS DATOS DEL ARRAYLIST 
        OrdenTrabajoCRUD otCRUD = new OrdenTrabajoCRUD(host);

        ot = otCRUD.visualizar(); // devuelve todos los registros de la BD

        for (OrdenTrabajos o : ot) {
            datos[0] = Integer.toString(o.getIdOrdtr());
            datos[1] = Integer.toString(o.getIdMant());
            datos[2] = o.getNroOrdtr();
            datos[3] = o.getDescOrdtr();
            datos[4] = o.getEstOrdtr();
            datos[5] = o.getTipoOrdtr();
            datos[6] = o.getPriorOrdtr();
            datos[7] = o.getFechHorSolicitudOrdtr();
            datos[8] = o.getFechHorReqOrdtr();
            datos[9] = o.getRespOrdtr();
            datos[10] = o.getInicioOrdtr();
            datos[11] = o.getTermOrdtr();
            datos[12] = o.getFechHoraEntOrdtr();
            datos[13] = Float.toString(o.getDuracionDiasOrdtr());
            datos[14] = o.getAceptPorOrdtr();
            datos[15] = o.getFallaOrdtr();
            datos[16] = o.getDescCausaOrdtr();
            datos[17] = o.getAccionRealizOrdtr();
            datos[18] = o.getPrevenTomadaOrdtr();
            model.addRow(datos);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab_ordentrabajo = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        cbox = new javax.swing.JComboBox<>();
        txtInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/show_all.png"))); // NOI18N
        jButton2.setText("Mostrar todo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/nuevo.png"))); // NOI18N
        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/edit.png"))); // NOI18N
        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/eliminar.png"))); // NOI18N
        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/door_exit.png"))); // NOI18N
        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        tab_ordentrabajo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Orden Trabajo", "Id Mantenimiento", "Número ", "Descripción ", "Estado ", "Tipo", "Prioridad", "Fecha Hora Solicitud", "Fecha Hora Requerida", "Respuesta", "Inicio", "Término", "Fecha Hora Entrega", "Duración Días", "Aceptado Por", "Falla", "Descripción Causa", "Acción Realizada", "Prevención Tomada"
            }
        ));
        tab_ordentrabajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_ordentrabajoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tab_ordentrabajo);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 620, 160));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Número de Orden", "Descripción", "Estado de Orden", "Tipo de Orden", "Prioridad", "Respuesta", "Inicio", "Término", "Aceptado por", "Falla", "Descripción de Causa", "Acción Realizada", "Prevención" }));
        cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxActionPerformed(evt);
            }
        });
        jPanel2.add(cbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, -1));

        txtInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputActionPerformed(evt);
            }
        });
        txtInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInputKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputKeyTyped(evt);
            }
        });
        jPanel2.add(txtInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 30, 140, -1));

        jLabel1.setText("Cantidad de Registros:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, 20));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 70, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 620, 80));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/excel_logo.png"))); // NOI18N
        jButton6.setToolTipText("Generar hoja de cálculo de Excel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 40, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 660, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Calendar calendario = new GregorianCalendar();
        int anio, mes, dia, hora, min, seg;
        anio = calendario.get(Calendar.YEAR);
        mes = calendario.get(Calendar.MONTH);
        dia = calendario.get(Calendar.DATE);
        hora = calendario.get(Calendar.HOUR_OF_DAY);
        min = calendario.get(Calendar.MINUTE);
        seg = calendario.get(Calendar.SECOND);
        String fecha = anio + "-" + mes + "-" + dia + " " + hora + ":" + min + ":" + seg;
        DefaultTableModel dtm = (DefaultTableModel) tab_ordentrabajo.getModel();
        int codOrden = Integer.parseInt(tab_ordentrabajo.getValueAt(tab_ordentrabajo.getSelectedRow(), 0).toString());
        ///OBTENGO LA FILA CON EL CODIGO RESPECTIVO
        OrdenTrabajoCRUD otCRUD = new OrdenTrabajoCRUD(host);
        OrdenTrabajos ot = new OrdenTrabajos();
        ot = otCRUD.mostrarPorCodigo(codOrden);
        //LA QUITO DE LA IMAGEN DE LA TABLA
        dtm.removeRow(tab_ordentrabajo.getSelectedRow());

        otCRUD.eliminar(ot, fecha, user);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        OrdenTrabajoNew obj = new OrdenTrabajoNew(user,host);
        Home.escritorio.add(obj);
        obj.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = obj.getSize();
        obj.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        obj.show();

        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //agregarDatos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

//        this.dispose();
        this.doDefaultCloseAction();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void tab_ordentrabajoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_ordentrabajoMouseClicked

    }//GEN-LAST:event_tab_ordentrabajoMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        OrdenTrabajoUpdate obj = new OrdenTrabajoUpdate(user,host);
        Home.escritorio.add(obj);
        obj.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = obj.getSize();
        obj.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        obj.show();

        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxActionPerformed
        txtInput.setText("");
    }//GEN-LAST:event_cboxActionPerformed

    private void txtInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputActionPerformed

    private void txtInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyReleased

        DefaultTableModel model = (DefaultTableModel) tab_ordentrabajo.getModel();
        model.setRowCount(0);
        OrdenTrabajoCRUD ot_query = new OrdenTrabajoCRUD(host);
        String datos[] = new String[20];//ARRAY DE 3
        if (txtInput.getText().isEmpty()) {

            for (int i = 0; i < tab_ordentrabajo.getRowCount(); i++) {
                modelo.removeRow(i);
                i -= 1;
            }

        } else {
            ot = ot_query.visualizar(txtInput.getText(), seleccionaritem());

            for (OrdenTrabajos o : ot) {
                datos[0] = Integer.toString(o.getIdOrdtr());
                datos[1] = Integer.toString(o.getIdMant());
                datos[2] = o.getNroOrdtr();
                datos[3] = o.getDescOrdtr();
                datos[4] = o.getEstOrdtr();
                datos[5] = o.getTipoOrdtr();
                datos[6] = o.getPriorOrdtr();
                datos[7] = o.getFechHorSolicitudOrdtr();
                datos[8] = o.getFechHorReqOrdtr();
                datos[9] = o.getRespOrdtr();
                datos[10] = o.getInicioOrdtr();
                datos[11] = o.getTermOrdtr();
                datos[12] = o.getFechHoraEntOrdtr();
                datos[13] = Float.toString(o.getDuracionDiasOrdtr());
                datos[14] = o.getAceptPorOrdtr();
                datos[15] = o.getFallaOrdtr();
                datos[16] = o.getDescCausaOrdtr();
                datos[17] = o.getAccionRealizOrdtr();
                datos[18] = o.getPrevenTomadaOrdtr();
                model.addRow(datos);
            }

        }
    }//GEN-LAST:event_txtInputKeyReleased

    private void txtInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyTyped
        //        String nombre = String.valueOf(cbox.getSelectedItem());
        //        System.out.println(nombre);
        //        String c = "Nombre";
        //        if (nombre.equals(c)) {
        //            char C = evt.getKeyChar();
        //            if (Character.isDigit(C)) {
        //
        //                evt.consume();
        //                txtInput.setCursor(null);
        //
        //            }
        //        } else {
        //
        //            char caracter = evt.getKeyChar();
        //
        //            // Verificar si la tecla pulsada no es un digito
        //            if (((caracter < '0')
        //                    || (caracter > '9'))
        //                    && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
        //                evt.consume();  // ignorar el evento de teclado
        //            }
        //
        //        }
    }//GEN-LAST:event_txtInputKeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        ReportsExcel reporte = new ReportsExcel(host);
        OrdenTrabajoCRUD eqCRUD = new OrdenTrabajoCRUD(host);
        ArrayList<OrdenTrabajos> ordsTra = eqCRUD.visualizar();
        if(reporte.escribirExcelOrdenesTrabajo(ordsTra)){
            JOptionPane.showMessageDialog(null, "ARCHIVO EXCEL DE ORDENES TRABAJO CREADO","ARCHIVO GUARDADO EXITOSAMENTE",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "ARCHIVO EXCEL DE ORDENES TRABAJO NO CREADO","EROOR EN GUARDADO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tab_ordentrabajo;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
