/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lubrindustrial.View;

import com.lubrindustrial.Server.Article;
import com.lubrindustrial.Server.ArticleCRUD;
import com.lubrindustrial.Server.PEDIDOMATERIAL;
import com.lubrindustrial.Server.PEDIDOMATERIALCRUD;
import static com.lubrindustrial.View.Home.escritorio;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcelo
 */
public class Pedidos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pedidos
     */
    
    
    DefaultTableModel modelo = new DefaultTableModel();
    
    ArrayList<PEDIDOMATERIAL> pedidos = new ArrayList<PEDIDOMATERIAL>();
    String host;
    
    public Pedidos() {
        try{
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
        initComponents();
        this.setIconifiable(true);
        this.setClosable(true);
        this.host = "";
        agregarDatos();
        tab_pedidos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tab_pedidos.doLayout();
        
    }
    
    public Pedidos(String hostname) {
        try{
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
        initComponents();
        this.setIconifiable(true);
        this.setClosable(true);
        this.host = hostname;
        agregarDatos();
        tab_pedidos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tab_pedidos.doLayout();
    }
    private void agregarDatos() {
        // ********** CAMBIO PARA MOSTRAR LAS 2 NUEVAS COLUMNAS DE LA BD

        DefaultTableModel model = (DefaultTableModel) tab_pedidos.getModel();

        model.setRowCount(0);
        String datos[] = new String[11];//ARRAY DE 3

        //LE PASO AL ARRAY LOS DATOS DEL ARRAYLIST 
        PEDIDOMATERIALCRUD pedCRUD = new PEDIDOMATERIALCRUD(host);

        pedidos = pedCRUD.visualizar(); // devuelve todos los registros de la BD

        for (PEDIDOMATERIAL p : pedidos) {

            datos[0] = Integer.toString(p.getIdPedido());
            datos[1] = p.getDescArt();
            datos[2] = Float.toString(p.getCantidad());
            datos[3] = p.getUnidadCantidad();
            datos[4] = p.getDescripcion();
            datos[5] = p.getDescEmpPedido();
            datos[6] = p.getDescEmpEntregado();
            datos[7] = p.getDescEmpAutorizado();
            datos[8] = p.getDescEmpAprobado();
            datos[9] = p.getFechaHoraSolicitud();
            datos[10] = p.getFechaHoraEntrega();
            
            model.addRow(datos);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab_pedidos = new javax.swing.JTable();
        btnShowAll = new javax.swing.JButton();
        btnNewPer = new javax.swing.JButton();

        setTitle("Pedidos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab_pedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Pedido", "Material", "Cantidad", "Unidad", "Descripción", "Pedido por", "Entregado a", "Autorizado por", "Aprobado por", "Fecha Hora Solicitud", "Fecha Hora Entrega "
            }
        ));
        tab_pedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_pedidosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tab_pedidos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 634, 160));

        btnShowAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/show_all.png"))); // NOI18N
        btnShowAll.setText("Mostrar todo");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });
        jPanel1.add(btnShowAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        btnNewPer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/nuevo.png"))); // NOI18N
        btnNewPer.setText("Registrar Pedido");
        btnNewPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPerActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 660, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab_pedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_pedidosMouseClicked

    }//GEN-LAST:event_tab_pedidosMouseClicked

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        // TODO add your handling code here:
        agregarDatos();
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void btnNewPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPerActionPerformed
        // TODO add your handling code here:
        PedidoMateriales obj = new PedidoMateriales(host);
        Home.escritorio.add(obj);
        obj.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = obj.getSize();
        obj.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        obj.show();
    }//GEN-LAST:event_btnNewPerActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Pedidos().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewPer;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tab_pedidos;
    // End of variables declaration//GEN-END:variables
}
