/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lubrindustrial.View;

import com.lubrindustrial.Server.Conexion;
import com.lubrindustrial.Server.OPERABILIDAD;
import com.lubrindustrial.Server.OPERABILIDADCRUD;
import com.lubrindustrial.Server.PERIODO;
import com.lubrindustrial.Server.PERIODOCRUD;
import com.lubrindustrial.Server.ReportsExcel;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Marcelo
 */
public class Periodos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Periodos
     */
    
    ArrayList<OPERABILIDAD> operabilidades = new ArrayList<OPERABILIDAD>();
    String host;
    Conexion con;
    Connection cn;
    
    public Periodos() {
        try{
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
        initComponents();
        this.setIconifiable(true);
        this.setClosable(true);
        this.host = "";
        llenarComboBoxOperabilidades();
        con = new Conexion(this.host);
        this.con.Conectar();
        cn =con.getCon();
        
    }
    
    public Periodos(String hostname) {
        try{
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
        initComponents();
        this.setIconifiable(true);
        this.setClosable(true);
        this.host = hostname;
        llenarComboBoxOperabilidades();
        con = new Conexion(this.host);
        this.con.Conectar();
        cn =con.getCon();
        
    }
    
    private void llenarComboBoxOperabilidades() {
        OPERABILIDADCRUD  opCRUD = new OPERABILIDADCRUD(host);

        operabilidades = opCRUD.visualizar(); // devuelve todos los registros de la BD

        comboOperabilidad.removeAllItems();

        for (OPERABILIDAD o : operabilidades) {
            comboOperabilidad.addItem(o.getIdOp() + " " + o.getDescripcion()+" "+o.getDescEquipo());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboOperabilidad = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        txAreaDatos = new java.awt.TextArea();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setTitle("Períodos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Seleccione la operabilidad del equipo ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 11, -1, -1));

        comboOperabilidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboOperabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 259, -1));

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 31, 118, -1));
        getContentPane().add(txAreaDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 490, 234));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/excel_logo.png"))); // NOI18N
        jButton5.setToolTipText("Generar hoja de cálculo de Excel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 40, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/pdf.png"))); // NOI18N
        jButton6.setToolTipText("Generar informe en PDF");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 40, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PERIODOCRUD perCRUD = new PERIODOCRUD(host);
        ArrayList<PERIODO> periodos = new ArrayList<PERIODO>();
        //int ultimo=0;
        float totalHoras=0.0f;
        String cad="";
        try {
            cad=comboOperabilidad.getSelectedItem().toString();
            String []split = cad.split(" ");
            cad = split[0]; // obtengo el id de operabilidad
            // obtengo los dtos del ultimo periodo de operabilidd segun el id
            periodos=perCRUD.visualizarHorasDiferenciaPorID(Integer.parseInt(cad));
            
            txAreaDatos.setText("");
            txAreaDatos.append(comboOperabilidad.getSelectedItem().toString()+"\n");
            for(PERIODO p : periodos){
                txAreaDatos.append("\n");
                txAreaDatos.append("Fecha Inicio: "+p.getFechaInicio()+"\n");
                txAreaDatos.append("Fecha Fin: "+p.getFechaFin()+"\n");
                txAreaDatos.append("Número Días: "+p.getDiasDiferencia()+"\n");
                txAreaDatos.append("Descripción: "+p.getDescipcionPeriodo()+"\n");
                txAreaDatos.append("Horas: "+p.getHorasPeriodo()+"\n");
                if(p.getActividadPeriodo()==1){
                    txAreaDatos.append("Actividad: ACTIVO \n");
                    totalHoras+=(p.getDiasDiferencia()*p.getHorasPeriodo());
                }else{
                    txAreaDatos.append("Actividad: INACTIVO \n");
                }
                    
                
            
                
                txAreaDatos.append("******************************************\n");
                
                
            }
            txAreaDatos.append("Total Horas: "+totalHoras);
//            if(periodos.get(ultimo).getActividadPeriodo()==0){
//                txt_ActividadUltima.setText("INACTIVO");
//            }else{
//                txt_ActividadUltima.setText("ACTIVO");
//            }
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error obtener los datos "+e.getMessage(), "ERROR DATOS", JOptionPane.ERROR_MESSAGE);
            System.out.println(""+e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        ReportsExcel reporte = new ReportsExcel(host);
        PERIODOCRUD eqCRUD = new PERIODOCRUD(host);
        ArrayList<PERIODO> per = eqCRUD.visualizar();
        if(reporte.escribirExcelPeriodosOperabilidad(per)){
            JOptionPane.showMessageDialog(null, "ARCHIVO EXCEL DE PERIODOS CREADO","ARCHIVO GUARDADO EXITOSAMENTE",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "ARCHIVO EXCEL DE PERIODOS NO CREADO","ERROR EN GUARDADO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        try {
             JasperReport reporte = null;
             String path = "src\\lubrindustrial\\periodos.jasper";
             reporte = (JasperReport)JRLoader.loadObjectFromFile(path);
             JasperPrint jprint = JasperFillManager.fillReport(reporte, null,this.cn);
//             JasperReport reporte = JasperCompileManager.compileReport("reportMantEmp2.jrxml");
//            JasperPrint print = JasperFillManager.fillReport(reporte, null, this.cn);
            JasperViewer jviewer = new JasperViewer(jprint,false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
            //JasperViewer.viewReport(print);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Periodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Periodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Periodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Periodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Periodos().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboOperabilidad;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private java.awt.TextArea txAreaDatos;
    // End of variables declaration//GEN-END:variables
}
