/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lubrindustrial.View;

import com.lubrindustrial.Server.OPERABILIDAD;
import com.lubrindustrial.Server.OPERABILIDADCRUD;
import com.lubrindustrial.Server.PERIODO;
import com.lubrindustrial.Server.PERIODOCRUD;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 *
 * @author Marcelo
 */
public class Periodos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Periodos
     */
    
    ArrayList<OPERABILIDAD> operabilidades = new ArrayList<OPERABILIDAD>();
    String host;
    
    public Periodos() {
        try{
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
        initComponents();
        this.setIconifiable(true);
        this.setClosable(true);
        this.host = "";
        llenarComboBoxOperabilidades();
        
    }
    
    public Periodos(String hostname) {
        try{
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
        initComponents();
        this.setIconifiable(true);
        this.setClosable(true);
        this.host = hostname;
        llenarComboBoxOperabilidades();
        
    }
    
    private void llenarComboBoxOperabilidades() {
        OPERABILIDADCRUD  opCRUD = new OPERABILIDADCRUD(host);

        operabilidades = opCRUD.visualizar(); // devuelve todos los registros de la BD

        comboOperabilidad.removeAllItems();

        for (OPERABILIDAD o : operabilidades) {
            comboOperabilidad.addItem(o.getIdOp() + " " + o.getDescripcion()+" "+o.getDescEquipo());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboOperabilidad = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        txAreaDatos = new java.awt.TextArea();

        setTitle("Períodos");

        jLabel1.setText("Seleccione la operabilidad del equipo ");

        comboOperabilidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txAreaDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(comboOperabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboOperabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txAreaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PERIODOCRUD perCRUD = new PERIODOCRUD(host);
        ArrayList<PERIODO> periodos = new ArrayList<PERIODO>();
        //int ultimo=0;
        float totalHoras=0.0f;
        String cad="";
        try {
            cad=comboOperabilidad.getSelectedItem().toString();
            String []split = cad.split(" ");
            cad = split[0]; // obtengo el id de operabilidad
            // obtengo los dtos del ultimo periodo de operabilidd segun el id
            periodos=perCRUD.visualizarHorasDiferenciaPorID(Integer.parseInt(cad));
            
            txAreaDatos.setText("");
            txAreaDatos.append(comboOperabilidad.getSelectedItem().toString()+"\n");
            for(PERIODO p : periodos){
                txAreaDatos.append("\n");
                txAreaDatos.append("Fecha Inicio: "+p.getFechaInicio()+"\n");
                txAreaDatos.append("Fecha Fin: "+p.getFechaFin()+"\n");
                txAreaDatos.append("Número Días: "+p.getDiasDiferencia()+"\n");
                txAreaDatos.append("Descripción: "+p.getDescipcionPeriodo()+"\n");
                txAreaDatos.append("Horas: "+p.getHorasPeriodo()+"\n");
                if(p.getActividadPeriodo()==1){
                    txAreaDatos.append("Actividad: ACTIVO \n");
                    totalHoras+=(p.getDiasDiferencia()*p.getHorasPeriodo());
                }else{
                    txAreaDatos.append("Actividad: INACTIVO \n");
                }
                    
                
            
                
                txAreaDatos.append("******************************************\n");
                
                
            }
            txAreaDatos.append("Total Horas: "+totalHoras);
//            if(periodos.get(ultimo).getActividadPeriodo()==0){
//                txt_ActividadUltima.setText("INACTIVO");
//            }else{
//                txt_ActividadUltima.setText("ACTIVO");
//            }
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error obtener los datos "+e.getMessage(), "ERROR DATOS", JOptionPane.ERROR_MESSAGE);
            System.out.println(""+e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Periodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Periodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Periodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Periodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Periodos().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboOperabilidad;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private java.awt.TextArea txAreaDatos;
    // End of variables declaration//GEN-END:variables
}
