/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lubrindustrial.View;

import com.lubrindustrial.Server.Conexion;
import com.lubrindustrial.Server.MantenimientoCRUD;
import com.lubrindustrial.Server.Mantenimientos;
import com.lubrindustrial.Server.OrdenTrabajoCRUD;
import com.lubrindustrial.Server.OrdenTrabajos;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JTable;
import javax.swing.UIManager;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Marcelo
 */
public class ReportOrdenCod extends javax.swing.JInternalFrame {
    ArrayList<OrdenTrabajos> ot = new ArrayList<OrdenTrabajos>();
    String host = "localhost";
    Conexion con;
    Connection cn;
    /**
     * Creates new form frmReportesOrdenesTrabajo
     */
    public ReportOrdenCod() {
        try{
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
        initComponents();
        llenarComboBoxOt();
        this.setIconifiable(true);
        this.setClosable(true);
        con = new Conexion(this.host);
        this.con.Conectar();
        cn =con.getCon();
    }
    
    public ReportOrdenCod(String hostname) {
        try{
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
        initComponents();
        llenarComboBoxOt();
        this.setIconifiable(true);
        this.setClosable(true);
        this.host = hostname;
        con = new Conexion(this.host);
        this.con.Conectar();
        cn =con.getCon();
        
    }
    
    private void llenarComboBoxOt() {
        OrdenTrabajoCRUD  otCRUD = new OrdenTrabajoCRUD();

        ot = otCRUD.visualizar(); // devuelve todos los registros de la BD
        comboOt.removeAllItems();

        for (OrdenTrabajos o : ot) {
            comboOt.addItem(o.getIdOrdtr() + " " + o.getDescOrdtr());
            //JOptionPane.showMessageDialog(null, m.getIdMantenimiento() + " " + m.getDescMantenimiento());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        botonBusqueda = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboOt = new javax.swing.JComboBox<>();
        prevTomdaOrdtr = new javax.swing.JTextField();
        txtMant = new javax.swing.JTextField();
        NroOrdtr = new javax.swing.JTextField();
        descOrdtr = new javax.swing.JTextField();
        estOrdtr = new javax.swing.JTextField();
        tipOrdtr = new javax.swing.JTextField();
        priorOrdtr = new javax.swing.JTextField();
        fechHorSolOrdtr = new javax.swing.JTextField();
        fechHorReqOrdtr = new javax.swing.JTextField();
        respOrdtr = new javax.swing.JTextField();
        iniOrdtr = new javax.swing.JTextField();
        terOrdtr = new javax.swing.JTextField();
        fechHorEntOrdtr = new javax.swing.JTextField();
        duraDiasOrdtr = new javax.swing.JTextField();
        aceptPorOrdtr = new javax.swing.JTextField();
        fallaOrdtr = new javax.swing.JTextField();
        descCausa = new javax.swing.JTextField();
        accRealOrdtr = new javax.swing.JTextField();
        btnGeneratePDF = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Nro. Orden Trabajo");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jLabel11.setText("Estado ");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        jLabel12.setText("Fecha Hora Solicitud ");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, 20));

        jLabel13.setText("Tipo ");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 20));

        jLabel18.setText("Fecha Hora Requerida");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, 20));

        jLabel19.setText("Respuesta");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, 20));

        jLabel20.setText("Fecha Inicio");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, 20));

        jLabel21.setText("Fecha Término ");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, 20));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cerrar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 100, 30));

        jLabel14.setText("Prioridad ");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        jLabel15.setText("Descripción ");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        jLabel1.setText("Mantenimiento");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel22.setText("Fecha Hora Entrega ");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, 20));

        jLabel23.setText("Duración Días ");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, 20));

        jLabel24.setText("Aceptado por");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, 20));

        jLabel25.setText("Falla");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, 20));

        jLabel26.setText("Descripción Causa");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, 20));

        jLabel27.setText("Acción Realizada");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, -1, 20));

        jLabel28.setText("Prevención Tomada");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, -1, 20));

        botonBusqueda.setText("Buscar");
        botonBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBusquedaActionPerformed(evt);
            }
        });
        jPanel3.add(botonBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 90, -1));

        jLabel4.setText("Id a Buscar");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 20));

        comboOt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(comboOt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 190, -1));

        prevTomdaOrdtr.setEditable(false);
        prevTomdaOrdtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevTomdaOrdtrActionPerformed(evt);
            }
        });
        jPanel3.add(prevTomdaOrdtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 130, -1));

        txtMant.setEditable(false);
        txtMant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMantActionPerformed(evt);
            }
        });
        jPanel3.add(txtMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 130, -1));

        NroOrdtr.setEditable(false);
        NroOrdtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NroOrdtrActionPerformed(evt);
            }
        });
        jPanel3.add(NroOrdtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 130, -1));

        descOrdtr.setEditable(false);
        descOrdtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descOrdtrActionPerformed(evt);
            }
        });
        jPanel3.add(descOrdtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 130, -1));

        estOrdtr.setEditable(false);
        estOrdtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estOrdtrActionPerformed(evt);
            }
        });
        jPanel3.add(estOrdtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 130, -1));

        tipOrdtr.setEditable(false);
        tipOrdtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipOrdtrActionPerformed(evt);
            }
        });
        jPanel3.add(tipOrdtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 130, -1));

        priorOrdtr.setEditable(false);
        priorOrdtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priorOrdtrActionPerformed(evt);
            }
        });
        jPanel3.add(priorOrdtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 130, -1));

        fechHorSolOrdtr.setEditable(false);
        fechHorSolOrdtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechHorSolOrdtrActionPerformed(evt);
            }
        });
        jPanel3.add(fechHorSolOrdtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 130, -1));

        fechHorReqOrdtr.setEditable(false);
        fechHorReqOrdtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechHorReqOrdtrActionPerformed(evt);
            }
        });
        jPanel3.add(fechHorReqOrdtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 130, -1));

        respOrdtr.setEditable(false);
        respOrdtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respOrdtrActionPerformed(evt);
            }
        });
        jPanel3.add(respOrdtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 130, -1));

        iniOrdtr.setEditable(false);
        iniOrdtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniOrdtrActionPerformed(evt);
            }
        });
        jPanel3.add(iniOrdtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 130, -1));

        terOrdtr.setEditable(false);
        terOrdtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terOrdtrActionPerformed(evt);
            }
        });
        jPanel3.add(terOrdtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 130, -1));

        fechHorEntOrdtr.setEditable(false);
        fechHorEntOrdtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechHorEntOrdtrActionPerformed(evt);
            }
        });
        jPanel3.add(fechHorEntOrdtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 130, -1));

        duraDiasOrdtr.setEditable(false);
        duraDiasOrdtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duraDiasOrdtrActionPerformed(evt);
            }
        });
        jPanel3.add(duraDiasOrdtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 130, -1));

        aceptPorOrdtr.setEditable(false);
        aceptPorOrdtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptPorOrdtrActionPerformed(evt);
            }
        });
        jPanel3.add(aceptPorOrdtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 130, -1));

        fallaOrdtr.setEditable(false);
        fallaOrdtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fallaOrdtrActionPerformed(evt);
            }
        });
        jPanel3.add(fallaOrdtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 130, -1));

        descCausa.setEditable(false);
        descCausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descCausaActionPerformed(evt);
            }
        });
        jPanel3.add(descCausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 130, -1));

        accRealOrdtr.setEditable(false);
        accRealOrdtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accRealOrdtrActionPerformed(evt);
            }
        });
        jPanel3.add(accRealOrdtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 130, -1));

        btnGeneratePDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/pdf.png"))); // NOI18N
        btnGeneratePDF.setText("Generar PDF");
        btnGeneratePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneratePDFActionPerformed(evt);
            }
        });
        jPanel3.add(btnGeneratePDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 180, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 830, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
//        Volver();
//        this.dispose();
        this.doDefaultCloseAction();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void botonBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBusquedaActionPerformed
        String codMant;
        codMant=comboOt.getSelectedItem().toString();
        String []splitD = codMant.split(" ");
        codMant = splitD[0];
        int codManti=Integer.parseInt(codMant);
        OrdenTrabajoCRUD otCRUD=new OrdenTrabajoCRUD();
        OrdenTrabajos ot=new OrdenTrabajos();
        ot=otCRUD.mostrarPorCodigo(codManti);
        txtMant.setEnabled(false);
        txtMant.setText(ot.getIdMant()+"");
        NroOrdtr.setText(ot.getNroOrdtr());
        accRealOrdtr.setText(ot.getAccionRealizOrdtr());
        aceptPorOrdtr.setText(ot.getAceptPorOrdtr());
        descCausa.setText(ot.getDescCausaOrdtr());
        descOrdtr.setText(ot.getDescOrdtr());
        duraDiasOrdtr.setText(ot.getDuracionDiasOrdtr()+"");
        estOrdtr.setText(ot.getEstOrdtr());
        fallaOrdtr.setText(ot.getFallaOrdtr());
        fechHorEntOrdtr.setText(ot.getFechHoraEntOrdtr());
        fechHorReqOrdtr.setText(ot.getFechHorReqOrdtr());
        fechHorSolOrdtr.setText(ot.getFechHorSolicitudOrdtr());
        iniOrdtr.setText(ot.getInicioOrdtr());
        prevTomdaOrdtr.setText(ot.getPrevenTomadaOrdtr());
        priorOrdtr.setText(ot.getPriorOrdtr());
        respOrdtr.setText(ot.getRespOrdtr());
        terOrdtr.setText(ot.getTermOrdtr());
        tipOrdtr.setText(ot.getTipoOrdtr());

    }//GEN-LAST:event_botonBusquedaActionPerformed

    private void prevTomdaOrdtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevTomdaOrdtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prevTomdaOrdtrActionPerformed

    private void txtMantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMantActionPerformed

    private void NroOrdtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NroOrdtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NroOrdtrActionPerformed

    private void descOrdtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descOrdtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descOrdtrActionPerformed

    private void estOrdtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estOrdtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estOrdtrActionPerformed

    private void tipOrdtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipOrdtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipOrdtrActionPerformed

    private void priorOrdtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priorOrdtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priorOrdtrActionPerformed

    private void fechHorSolOrdtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechHorSolOrdtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechHorSolOrdtrActionPerformed

    private void fechHorReqOrdtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechHorReqOrdtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechHorReqOrdtrActionPerformed

    private void respOrdtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respOrdtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respOrdtrActionPerformed

    private void iniOrdtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniOrdtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniOrdtrActionPerformed

    private void terOrdtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terOrdtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terOrdtrActionPerformed

    private void fechHorEntOrdtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechHorEntOrdtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechHorEntOrdtrActionPerformed

    private void duraDiasOrdtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duraDiasOrdtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duraDiasOrdtrActionPerformed

    private void aceptPorOrdtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptPorOrdtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptPorOrdtrActionPerformed

    private void fallaOrdtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fallaOrdtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fallaOrdtrActionPerformed

    private void descCausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descCausaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descCausaActionPerformed

    private void accRealOrdtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accRealOrdtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accRealOrdtrActionPerformed

    private void btnGeneratePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratePDFActionPerformed
        
        String cad="";
        try {
            cad=comboOt.getSelectedItem().toString();
            String []split = cad.split(" ");
            cad = split[0];
             JasperReport reporte = null;
             String path = "src\\lubrindustrial\\ordentrabCod.jasper";
             Map parametro = new HashMap();
             parametro.put("id_ordtr",cad);
             reporte = (JasperReport)JRLoader.loadObjectFromFile(path);
             JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro,this.cn);
//             JasperReport reporte = JasperCompileManager.compileReport("reportMantEmp2.jrxml");
//            JasperPrint print = JasperFillManager.fillReport(reporte, null, this.cn);
            JasperViewer jviewer = new JasperViewer(jprint,false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
            //JasperViewer.viewReport(print);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
//        try {
//             JasperReport reporte = null;
//             String path = "src\\lubrindustrial\\materiales.jasper";
//             reporte = (JasperReport)JRLoader.loadObjectFromFile(path);
//             JasperPrint jprint = JasperFillManager.fillReport(reporte, null,this.cn);
////             JasperReport reporte = JasperCompileManager.compileReport("reportMantEmp2.jrxml");
////            JasperPrint print = JasperFillManager.fillReport(reporte, null, this.cn);
//            JasperViewer jviewer = new JasperViewer(jprint,false);
//            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//            jviewer.setVisible(true);
//            //JasperViewer.viewReport(print);
//        } catch (Exception e) {
//            System.out.println(e.getMessage());
//        }
//        
//        try {
//            JasperReport reporte = JasperCompileManager.compileReport("reportOrdTrabCod1.jrxml");
//            JasperPrint print = JasperFillManager.fillReport(reporte, null, this.cn);
//            JasperViewer jviewer = new JasperViewer(print,false);
//            jviewer.show();
//            //JasperViewer.viewReport(print);
//
//        } catch (Exception e) {
//            System.out.println(e.getMessage());
//        }
    }//GEN-LAST:event_btnGeneratePDFActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ReportOrdenCod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ReportOrdenCod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ReportOrdenCod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ReportOrdenCod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ReportOrdenCod().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NroOrdtr;
    private javax.swing.JTextField accRealOrdtr;
    private javax.swing.JTextField aceptPorOrdtr;
    private javax.swing.JButton botonBusqueda;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGeneratePDF;
    private javax.swing.JComboBox<String> comboOt;
    private javax.swing.JTextField descCausa;
    private javax.swing.JTextField descOrdtr;
    private javax.swing.JTextField duraDiasOrdtr;
    private javax.swing.JTextField estOrdtr;
    private javax.swing.JTextField fallaOrdtr;
    private javax.swing.JTextField fechHorEntOrdtr;
    private javax.swing.JTextField fechHorReqOrdtr;
    private javax.swing.JTextField fechHorSolOrdtr;
    private javax.swing.JTextField iniOrdtr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField prevTomdaOrdtr;
    private javax.swing.JTextField priorOrdtr;
    private javax.swing.JTextField respOrdtr;
    private javax.swing.JTextField terOrdtr;
    private javax.swing.JTextField tipOrdtr;
    private javax.swing.JTextField txtMant;
    // End of variables declaration//GEN-END:variables
}
