/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lubrindustrial.View;

import com.lubrindustrial.Server.Conexion;
import com.lubrindustrial.Server.Employee;
import com.lubrindustrial.Server.EmployeeCRUD;
import com.lubrindustrial.Server.Instruction;
import com.lubrindustrial.Server.InstructionCRUD;
import com.lubrindustrial.Server.MantenimientoCRUD;
import com.lubrindustrial.Server.Mantenimientos;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Marcelo
 */
public class ReportMantenimientoCod extends javax.swing.JInternalFrame {
        DefaultListModel modeloLista = new DefaultListModel();
    DefaultListModel modeloLista1 = new DefaultListModel();
    ArrayList<Mantenimientos> mante = new ArrayList<Mantenimientos>();
    String host = "localhost";
    Conexion con;
    Connection cn;
    
    /**
     * Creates new form frmReportesMantenimientos
     */
    public ReportMantenimientoCod() {
        try{
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
        initComponents();
        llenarComboBoxMant();
        listaEmpleados.setModel(modeloLista);
        listaInstrucciones.setModel(modeloLista1);
        this.setIconifiable(true);
        this.setClosable(true);
        con = new Conexion(this.host);
        this.con.Conectar();
        cn =con.getCon();
    }
    
    public ReportMantenimientoCod(String hostname) {
        try{
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
        initComponents();
        llenarComboBoxMant();
        listaEmpleados.setModel(modeloLista);
        listaInstrucciones.setModel(modeloLista1);
        this.setIconifiable(true);
        this.setClosable(true);
        this.host = hostname;
        con = new Conexion(this.host);
        this.con.Conectar();
        cn =con.getCon();
        
    }
    
    private void llenarComboBoxMant() {
        MantenimientoCRUD  mantCRUD = new MantenimientoCRUD();

        mante = mantCRUD.visualizar(); // devuelve todos los registros de la BD
        comboMant.removeAllItems();

        for (Mantenimientos m : mante) {
            comboMant.addItem(m.getIdMantenimiento() + " " + m.getDescMantenimiento());
            //JOptionPane.showMessageDialog(null, m.getIdMantenimiento() + " " + m.getDescMantenimiento());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        horasProgramadas = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonBusqueda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEmpleados = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaInstrucciones = new javax.swing.JList<>();
        jLabel22 = new javax.swing.JLabel();
        comboMant = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtEqLoc = new javax.swing.JTextField();
        durTareaMantenimiento1 = new javax.swing.JTextField();
        txtNroTareaMant = new javax.swing.JTextField();
        desMantenimiento = new javax.swing.JTextField();
        oficioMant = new javax.swing.JTextField();
        frecMantenimiento = new javax.swing.JTextField();
        diasMantenimiento = new javax.swing.JTextField();
        fechInicioMant = new javax.swing.JTextField();
        fechProgIniMant = new javax.swing.JTextField();
        fechProgTermMant = new javax.swing.JTextField();
        proxFechMant = new javax.swing.JTextField();
        btnGeneratePDF = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Id Mantenimiento a mostrar");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 20));

        jLabel9.setText("Nro. Tarea Mantenimiento");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 20));

        jLabel11.setText("Oficio Mantenimiento");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));

        jLabel12.setText("Duración Tareas Mantenimiento");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 20));

        jLabel13.setText("Frecuencia Mantenimiento");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 20));

        jLabel18.setText("Fecha Inicio Mantenimiento");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, 20));

        jLabel19.setText("Fecha Programada Inicio Mant.");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, 20));

        jLabel20.setText("Fecha Programada Término Mant.");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, 20));

        jLabel21.setText("Próxima Fecha Mantenimiento");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, 20));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cerrar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, 30));

        jLabel14.setText("Días Mantenimiento");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 20));

        horasProgramadas.setEditable(false);
        horasProgramadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horasProgramadasActionPerformed(evt);
            }
        });
        jPanel3.add(horasProgramadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 150, -1));

        jLabel15.setText("Descripción Mantenimiento");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 20));

        jLabel2.setText("Instrucciones");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        jLabel3.setText("Empleados");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        botonBusqueda.setText("Buscar");
        botonBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBusquedaActionPerformed(evt);
            }
        });
        jPanel3.add(botonBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 90, -1));

        listaEmpleados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaEmpleados);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 210, 80));

        listaInstrucciones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaInstrucciones);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 210, 80));

        jLabel22.setText("Horas Programadas");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 120, 20));

        comboMant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMant.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboMantItemStateChanged(evt);
            }
        });
        comboMant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboMantMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                comboMantMouseExited(evt);
            }
        });
        comboMant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMantActionPerformed(evt);
            }
        });
        jPanel3.add(comboMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 210, -1));

        jLabel1.setText("Localización o Equipo");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 20));

        txtEqLoc.setEditable(false);
        jPanel3.add(txtEqLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 150, -1));

        durTareaMantenimiento1.setEditable(false);
        jPanel3.add(durTareaMantenimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 120, -1));

        txtNroTareaMant.setEditable(false);
        txtNroTareaMant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNroTareaMantActionPerformed(evt);
            }
        });
        jPanel3.add(txtNroTareaMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 150, -1));

        desMantenimiento.setEditable(false);
        desMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desMantenimientoActionPerformed(evt);
            }
        });
        jPanel3.add(desMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 150, -1));

        oficioMant.setEditable(false);
        oficioMant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oficioMantActionPerformed(evt);
            }
        });
        jPanel3.add(oficioMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 150, -1));

        frecMantenimiento.setEditable(false);
        frecMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frecMantenimientoActionPerformed(evt);
            }
        });
        jPanel3.add(frecMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 150, -1));

        diasMantenimiento.setEditable(false);
        diasMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diasMantenimientoActionPerformed(evt);
            }
        });
        jPanel3.add(diasMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 150, -1));

        fechInicioMant.setEditable(false);
        fechInicioMant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechInicioMantActionPerformed(evt);
            }
        });
        jPanel3.add(fechInicioMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 150, -1));

        fechProgIniMant.setEditable(false);
        fechProgIniMant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechProgIniMantActionPerformed(evt);
            }
        });
        jPanel3.add(fechProgIniMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 150, -1));

        fechProgTermMant.setEditable(false);
        fechProgTermMant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechProgTermMantActionPerformed(evt);
            }
        });
        jPanel3.add(fechProgTermMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 150, -1));

        proxFechMant.setEditable(false);
        proxFechMant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proxFechMantActionPerformed(evt);
            }
        });
        jPanel3.add(proxFechMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 150, -1));

        btnGeneratePDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/pdf.png"))); // NOI18N
        btnGeneratePDF.setText("Generar PDF");
        btnGeneratePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneratePDFActionPerformed(evt);
            }
        });
        jPanel3.add(btnGeneratePDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 150, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 720, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBusquedaActionPerformed
        
        String codMant;
        codMant=comboMant.getSelectedItem().toString();
        String []splitD = codMant.split(" ");
        codMant = splitD[0];
        int codManti=Integer.parseInt(codMant);
        MantenimientoCRUD mantCRUD=new MantenimientoCRUD();
        Mantenimientos m=new Mantenimientos();
//        JOptionPane.showMessageDialog(null, "codigo mant: "+codManti);
        m=mantCRUD.mostrarPorCodigo(codManti);
        if(m.getIdEquipo()!=0)
            txtEqLoc.setText(m.getIdEquipo()+"");
        else
            txtEqLoc.setText(m.getIdLocacion()+"");
        diasMantenimiento.setText(m.getDiasMant()+"");
        desMantenimiento.setText(m.getDescMantenimiento()+"");
        horasProgramadas.setText(m.getDurTareaMant()+"");
        fechInicioMant.setText(m.getFechIniMantenimiento()+"");
        fechProgIniMant.setText(m.getFechProgInicMant()+"");
        fechProgTermMant.setText(m.getFechProgTermMant()+"");
        frecMantenimiento.setText(m.getFrecuenciaMant()+"");
        oficioMant.setText(m.getOficioMantenimiento()+"");
        proxFechMant.setText(m.getFechProximaMant()+"");
        txtNroTareaMant.setText(m.getNroTareaMant()+"");
        horasProgramadas.setText(m.getHorasProgramadas()+"");
        
        EmployeeCRUD empCRUD=new EmployeeCRUD();
        ArrayList<Employee> listaEmp=new ArrayList<Employee>();
        listaEmp=empCRUD.mostrarPorCodigo(codManti);
        for(int i=0;i<listaEmp.size();i++)
        {
            //JOptionPane.showMessageDialog(null, );
            modeloLista.addElement(listaEmp.get(i).getIdEmployee()+" "+listaEmp.get(i).getNomEmployee()+" "+listaEmp.get(i).getApeEmployee());
        }
        
        //Datos instrucciones
        InstructionCRUD instCRUD=new InstructionCRUD();
        ArrayList<Instruction> listaInst=new ArrayList<Instruction>();
        listaInst=instCRUD.mostrarPorCodigo(codManti);
        for(int i=0;i<listaInst.size();i++)
        {
            modeloLista1.addElement(listaInst.get(i).getIdInst()+" "+listaInst.get(i).getDescInst());
        }
        
    }//GEN-LAST:event_botonBusquedaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
//        Volver();
//        this.dispose();
        this.doDefaultCloseAction();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void comboMantMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMantMouseExited
        
    }//GEN-LAST:event_comboMantMouseExited

    private void comboMantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMantActionPerformed
        //JOptionPane.showMessageDialog(null, "Esto hace: ");
        ////ACCION A REALIZAR CUANDO SE BUSQUE POR CODIGO
        
        
    }//GEN-LAST:event_comboMantActionPerformed

    private void comboMantItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboMantItemStateChanged

    }//GEN-LAST:event_comboMantItemStateChanged

    private void comboMantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMantMouseClicked
        
    }//GEN-LAST:event_comboMantMouseClicked

    private void horasProgramadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horasProgramadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horasProgramadasActionPerformed

    private void txtNroTareaMantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroTareaMantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNroTareaMantActionPerformed

    private void desMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desMantenimientoActionPerformed

    private void oficioMantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oficioMantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oficioMantActionPerformed

    private void frecMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frecMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frecMantenimientoActionPerformed

    private void diasMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diasMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diasMantenimientoActionPerformed

    private void fechInicioMantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechInicioMantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechInicioMantActionPerformed

    private void fechProgIniMantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechProgIniMantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechProgIniMantActionPerformed

    private void fechProgTermMantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechProgTermMantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechProgTermMantActionPerformed

    private void proxFechMantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxFechMantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proxFechMantActionPerformed

    private void btnGeneratePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratePDFActionPerformed
        String cad="";
        try {
            cad=comboMant.getSelectedItem().toString();
            String []split = cad.split(" ");
            cad = split[0];
             JasperReport reporte = null;
             String path = "src\\lubrindustrial\\mantenimientoCod.jasper";
             Map parametro = new HashMap();
             parametro.put("id_mant",cad);
             reporte = (JasperReport)JRLoader.loadObjectFromFile(path);
             JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro,this.cn);
//             JasperReport reporte = JasperCompileManager.compileReport("reportMantEmp2.jrxml");
//            JasperPrint print = JasperFillManager.fillReport(reporte, null, this.cn);
            JasperViewer jviewer = new JasperViewer(jprint,false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
            //JasperViewer.viewReport(print);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
//        try {
//            JasperReport reporte = JasperCompileManager.compileReport("reportMantCod1.jrxml");
//            //JasperReport reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/Reportes/reportMantCod1.jrxml"));
//            JasperPrint print = JasperFillManager.fillReport(reporte, null, this.cn);
//            JasperViewer jviewer = new JasperViewer(print,false);
//            jviewer.show();
//            //JasperViewer.viewReport(print);
//        } catch (Exception e) {
//            System.out.println(e.getMessage());
//        }
       
    }//GEN-LAST:event_btnGeneratePDFActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ReportMantenimientoCod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ReportMantenimientoCod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ReportMantenimientoCod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ReportMantenimientoCod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ReportMantenimientoCod().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBusqueda;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGeneratePDF;
    private javax.swing.JComboBox<String> comboMant;
    private javax.swing.JTextField desMantenimiento;
    private javax.swing.JTextField diasMantenimiento;
    private javax.swing.JTextField durTareaMantenimiento1;
    private javax.swing.JTextField fechInicioMant;
    private javax.swing.JTextField fechProgIniMant;
    private javax.swing.JTextField fechProgTermMant;
    private javax.swing.JTextField frecMantenimiento;
    private javax.swing.JTextField horasProgramadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaEmpleados;
    private javax.swing.JList<String> listaInstrucciones;
    private javax.swing.JTextField oficioMant;
    private javax.swing.JTextField proxFechMant;
    private javax.swing.JTextField txtEqLoc;
    private javax.swing.JTextField txtNroTareaMant;
    // End of variables declaration//GEN-END:variables
}
