/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lubrindustrial.View;

import com.lubrindustrial.Server.Hasher;
import com.lubrindustrial.Server.User;
import com.lubrindustrial.Server.UserCRUD;
import static com.lubrindustrial.View.Home.escritorio;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.awt.Cursor;
import java.awt.Dimension;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

public class ResetPassword extends javax.swing.JFrame {

    Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
    ArrayList<User> use = new ArrayList<User>();
    String host;
    public static int cuentaEmpleado;

    public ResetPassword() {
        try{
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
        initComponents();
        this.setLocationRelativeTo(null);
        lblCuenta.setVisible(false);
        lblCuenta.setEnabled(false);
        lblPassAct.setVisible(false);
        lblPassAct.setEnabled(false);
        txtPassAct.setVisible(false);
        txtPassAct.setEnabled(false);
    }

    public ResetPassword(String hostname) {
        try{
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        }catch(Exception e){
            System.err.println(e.getMessage());
        }
        initComponents();
        this.setLocationRelativeTo(null);
        lblCuenta.setVisible(false);
        lblCuenta.setEnabled(false);
        this.host = hostname;
        lblPassAct.setVisible(false);
        lblPassAct.setEnabled(false);
        txtPassAct.setVisible(false);
        txtPassAct.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel_newPass = new javax.swing.JPanel();
        txtPassAct = new javax.swing.JPasswordField();
        lblPassAct = new javax.swing.JLabel();
        txtPassNew = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        txtPassRep = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblCuenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel1.setText("Recuperar contraseña");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 181, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/login.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 11, -1, 300));

        jPanel_newPass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPassAct.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jPanel_newPass.add(txtPassAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 230, -1));

        lblPassAct.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPassAct.setForeground(new java.awt.Color(51, 51, 255));
        lblPassAct.setText("CONTRASEÑA ACTUAL:");
        jPanel_newPass.add(lblPassAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtPassNew.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jPanel_newPass.add(txtPassNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 230, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("CONTRASEÑA NUEVA:");
        jPanel_newPass.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txtPassRep.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jPanel_newPass.add(txtPassRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 230, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("REPITA LA CONTRASEÑA NUEVA:");
        jPanel_newPass.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/door_exit.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.setName(""); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel_newPass.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 100, -1));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lubrindustrial/Icons/actu.png"))); // NOI18N
        btnSave.setText("Guardar");
        btnSave.setName(""); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel_newPass.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jPanel1.add(jPanel_newPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 260, 240));

        lblCuenta.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int contador = 0;
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            if (/*txtPassAct.getText().length() > 0 && */txtPassNew.getText().length() > 0 && txtPassRep.getText().length() > 0) {

                String datos[] = new String[8];//ARRAY DE 8
                UserCRUD query = new UserCRUD(this.host);
                use = query.visualizar(lblCuenta.getText());

                for (User u : use) {
                    datos[0] = Integer.toString(u.getIdUser());
                    datos[1] = u.getNomUser();
                    datos[2] = u.getApeUser();
                    datos[3] = u.getPreg1User();
                    datos[4] = u.getPreg2User();
                    datos[5] = u.getUsuUser();
                    datos[6] = u.getPassUser();
                    datos[7] = Integer.toString(u.getActivoUser());

                }

                if (datos[7].equals("1")) {
//                    if (datos[6].equals(Hasher.convertToMD5(Hasher.convertToSHA1(Hasher.convertToSHA1(txtPassAct.getText())))) == true) {
                        if (txtPassNew.getText().equals(txtPassRep.getText())) {
                            for (User u : use) {
                                u.setPassUser(Hasher.convertToMD5(Hasher.convertToSHA1(Hasher.convertToSHA1(txtPassNew.getText()))));
                                query.modificar(u);
                                JOptionPane.showMessageDialog(null, "La contraseña ha sido cambiada correctamente", "Contraseña Cambiada", JOptionPane.INFORMATION_MESSAGE);
                                Login log = new Login();
                                log.setVisible(true);
                                log.setEnabled(true);
                                this.dispose();
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "No coinciden los campos de contraseña ", "Contraseña Nueva", JOptionPane.WARNING_MESSAGE);
                        }
//                    } else {
//                        contador++;
//                        JOptionPane.showMessageDialog(null, "Datos incorrectos. Número de intentos: " + contador, "Incorrecto", JOptionPane.WARNING_MESSAGE);
//                        if (contador == 3) {
//                            JOptionPane.showMessageDialog(null, "Ha llegado al número máximo de intentos (" + contador + ")", "Cerrando...", JOptionPane.WARNING_MESSAGE);
//                            System.exit(0);
//                        }
//                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El usuario se encuentra deshabilitado, no es posible usarlo", "Usuario Inhabilitado", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debe ingresar todos los campos", "Completar", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "No se ha encontrado el usuario", "Usuario no registrado", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed

        ValidateQuestion obj = new ValidateQuestion();
        obj.setVisible(true);
        obj.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_newPass;
    public static javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblPassAct;
    private javax.swing.JPasswordField txtPassAct;
    private javax.swing.JPasswordField txtPassNew;
    private javax.swing.JPasswordField txtPassRep;
    // End of variables declaration//GEN-END:variables
}
